/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The August model module.
 * @module model/August
 * @version 1.0.0
 */
class August {
    /**
     * Constructs a new <code>August</code>.
     * @alias module:model/August
     * @param employee {module:model/User} 
     * @param day1 {String} 
     * @param day2 {String} 
     * @param day3 {String} 
     * @param day4 {String} 
     * @param day5 {String} 
     * @param day6 {String} 
     * @param day7 {String} 
     * @param day8 {String} 
     * @param day9 {String} 
     * @param day10 {String} 
     * @param day11 {String} 
     * @param day12 {String} 
     * @param day13 {String} 
     * @param day14 {String} 
     * @param day15 {String} 
     * @param day16 {String} 
     * @param day17 {String} 
     * @param day18 {String} 
     * @param day19 {String} 
     * @param day20 {String} 
     * @param day21 {String} 
     * @param day22 {String} 
     */
    constructor(employee, day1, day2, day3, day4, day5, day6, day7, day8, day9, day10, day11, day12, day13, day14, day15, day16, day17, day18, day19, day20, day21, day22) { 
        
        August.initialize(this, employee, day1, day2, day3, day4, day5, day6, day7, day8, day9, day10, day11, day12, day13, day14, day15, day16, day17, day18, day19, day20, day21, day22);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, employee, day1, day2, day3, day4, day5, day6, day7, day8, day9, day10, day11, day12, day13, day14, day15, day16, day17, day18, day19, day20, day21, day22) { 
        obj['employee'] = employee;
        obj['day1'] = day1;
        obj['day2'] = day2;
        obj['day3'] = day3;
        obj['day4'] = day4;
        obj['day5'] = day5;
        obj['day6'] = day6;
        obj['day7'] = day7;
        obj['day8'] = day8;
        obj['day9'] = day9;
        obj['day10'] = day10;
        obj['day11'] = day11;
        obj['day12'] = day12;
        obj['day13'] = day13;
        obj['day14'] = day14;
        obj['day15'] = day15;
        obj['day16'] = day16;
        obj['day17'] = day17;
        obj['day18'] = day18;
        obj['day19'] = day19;
        obj['day20'] = day20;
        obj['day21'] = day21;
        obj['day22'] = day22;
    }

    /**
     * Constructs a <code>August</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/August} obj Optional instance to populate.
     * @return {module:model/August} The populated <code>August</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new August();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('employee')) {
                obj['employee'] = ApiClient.convertToType(data['employee'], User);
            }
            if (data.hasOwnProperty('day1')) {
                obj['day1'] = ApiClient.convertToType(data['day1'], 'String');
            }
            if (data.hasOwnProperty('day2')) {
                obj['day2'] = ApiClient.convertToType(data['day2'], 'String');
            }
            if (data.hasOwnProperty('day3')) {
                obj['day3'] = ApiClient.convertToType(data['day3'], 'String');
            }
            if (data.hasOwnProperty('day4')) {
                obj['day4'] = ApiClient.convertToType(data['day4'], 'String');
            }
            if (data.hasOwnProperty('day5')) {
                obj['day5'] = ApiClient.convertToType(data['day5'], 'String');
            }
            if (data.hasOwnProperty('day6')) {
                obj['day6'] = ApiClient.convertToType(data['day6'], 'String');
            }
            if (data.hasOwnProperty('day7')) {
                obj['day7'] = ApiClient.convertToType(data['day7'], 'String');
            }
            if (data.hasOwnProperty('day8')) {
                obj['day8'] = ApiClient.convertToType(data['day8'], 'String');
            }
            if (data.hasOwnProperty('day9')) {
                obj['day9'] = ApiClient.convertToType(data['day9'], 'String');
            }
            if (data.hasOwnProperty('day10')) {
                obj['day10'] = ApiClient.convertToType(data['day10'], 'String');
            }
            if (data.hasOwnProperty('day11')) {
                obj['day11'] = ApiClient.convertToType(data['day11'], 'String');
            }
            if (data.hasOwnProperty('day12')) {
                obj['day12'] = ApiClient.convertToType(data['day12'], 'String');
            }
            if (data.hasOwnProperty('day13')) {
                obj['day13'] = ApiClient.convertToType(data['day13'], 'String');
            }
            if (data.hasOwnProperty('day14')) {
                obj['day14'] = ApiClient.convertToType(data['day14'], 'String');
            }
            if (data.hasOwnProperty('day15')) {
                obj['day15'] = ApiClient.convertToType(data['day15'], 'String');
            }
            if (data.hasOwnProperty('day16')) {
                obj['day16'] = ApiClient.convertToType(data['day16'], 'String');
            }
            if (data.hasOwnProperty('day17')) {
                obj['day17'] = ApiClient.convertToType(data['day17'], 'String');
            }
            if (data.hasOwnProperty('day18')) {
                obj['day18'] = ApiClient.convertToType(data['day18'], 'String');
            }
            if (data.hasOwnProperty('day19')) {
                obj['day19'] = ApiClient.convertToType(data['day19'], 'String');
            }
            if (data.hasOwnProperty('day20')) {
                obj['day20'] = ApiClient.convertToType(data['day20'], 'String');
            }
            if (data.hasOwnProperty('day21')) {
                obj['day21'] = ApiClient.convertToType(data['day21'], 'String');
            }
            if (data.hasOwnProperty('day22')) {
                obj['day22'] = ApiClient.convertToType(data['day22'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
August.prototype['_id'] = undefined;

/**
 * @member {module:model/User} employee
 */
August.prototype['employee'] = undefined;

/**
 * @member {String} day1
 */
August.prototype['day1'] = undefined;

/**
 * @member {String} day2
 */
August.prototype['day2'] = undefined;

/**
 * @member {String} day3
 */
August.prototype['day3'] = undefined;

/**
 * @member {String} day4
 */
August.prototype['day4'] = undefined;

/**
 * @member {String} day5
 */
August.prototype['day5'] = undefined;

/**
 * @member {String} day6
 */
August.prototype['day6'] = undefined;

/**
 * @member {String} day7
 */
August.prototype['day7'] = undefined;

/**
 * @member {String} day8
 */
August.prototype['day8'] = undefined;

/**
 * @member {String} day9
 */
August.prototype['day9'] = undefined;

/**
 * @member {String} day10
 */
August.prototype['day10'] = undefined;

/**
 * @member {String} day11
 */
August.prototype['day11'] = undefined;

/**
 * @member {String} day12
 */
August.prototype['day12'] = undefined;

/**
 * @member {String} day13
 */
August.prototype['day13'] = undefined;

/**
 * @member {String} day14
 */
August.prototype['day14'] = undefined;

/**
 * @member {String} day15
 */
August.prototype['day15'] = undefined;

/**
 * @member {String} day16
 */
August.prototype['day16'] = undefined;

/**
 * @member {String} day17
 */
August.prototype['day17'] = undefined;

/**
 * @member {String} day18
 */
August.prototype['day18'] = undefined;

/**
 * @member {String} day19
 */
August.prototype['day19'] = undefined;

/**
 * @member {String} day20
 */
August.prototype['day20'] = undefined;

/**
 * @member {String} day21
 */
August.prototype['day21'] = undefined;

/**
 * @member {String} day22
 */
August.prototype['day22'] = undefined;






export default August;

