/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Day model module.
 * @module model/Day
 * @version 1.0.0
 */
class Day {
    /**
     * Constructs a new <code>Day</code>.
     * @alias module:model/Day
     * @param dayId {String} 
     * @param dayDate {Date} 
     * @param dayHours {Number} 
     */
    constructor(dayId, dayDate, dayHours) { 
        
        Day.initialize(this, dayId, dayDate, dayHours);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, dayId, dayDate, dayHours) { 
        obj['dayId'] = dayId;
        obj['dayDate'] = dayDate;
        obj['dayHours'] = dayHours;
    }

    /**
     * Constructs a <code>Day</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Day} obj Optional instance to populate.
     * @return {module:model/Day} The populated <code>Day</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Day();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('dayId')) {
                obj['dayId'] = ApiClient.convertToType(data['dayId'], 'String');
            }
            if (data.hasOwnProperty('dayDate')) {
                obj['dayDate'] = ApiClient.convertToType(data['dayDate'], 'Date');
            }
            if (data.hasOwnProperty('dayHours')) {
                obj['dayHours'] = ApiClient.convertToType(data['dayHours'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Day.prototype['_id'] = undefined;

/**
 * @member {String} dayId
 */
Day.prototype['dayId'] = undefined;

/**
 * @member {Date} dayDate
 */
Day.prototype['dayDate'] = undefined;

/**
 * @member {Number} dayHours
 */
Day.prototype['dayHours'] = undefined;






export default Day;

