/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The December model module.
 * @module model/December
 * @version 1.0.0
 */
class December {
    /**
     * Constructs a new <code>December</code>.
     * @alias module:model/December
     * @param decDay1 {String} 
     * @param decDay2 {String} 
     * @param decDay3 {String} 
     * @param decDay4 {String} 
     * @param decDay5 {String} 
     * @param decDay6 {String} 
     * @param decDay7 {String} 
     * @param decDay8 {String} 
     * @param decDay9 {String} 
     * @param decDay10 {String} 
     * @param decDay11 {String} 
     * @param decDay12 {String} 
     * @param decDay13 {String} 
     * @param decDay14 {String} 
     * @param decDay15 {String} 
     * @param decDay16 {String} 
     * @param decDay17 {String} 
     * @param decDay18 {String} 
     * @param decDay19 {String} 
     * @param decDay20 {String} 
     * @param decDay21 {String} 
     * @param employeeDec {module:model/User} 
     */
    constructor(decDay1, decDay2, decDay3, decDay4, decDay5, decDay6, decDay7, decDay8, decDay9, decDay10, decDay11, decDay12, decDay13, decDay14, decDay15, decDay16, decDay17, decDay18, decDay19, decDay20, decDay21, employeeDec) { 
        
        December.initialize(this, decDay1, decDay2, decDay3, decDay4, decDay5, decDay6, decDay7, decDay8, decDay9, decDay10, decDay11, decDay12, decDay13, decDay14, decDay15, decDay16, decDay17, decDay18, decDay19, decDay20, decDay21, employeeDec);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, decDay1, decDay2, decDay3, decDay4, decDay5, decDay6, decDay7, decDay8, decDay9, decDay10, decDay11, decDay12, decDay13, decDay14, decDay15, decDay16, decDay17, decDay18, decDay19, decDay20, decDay21, employeeDec) { 
        obj['decDay1'] = decDay1;
        obj['decDay2'] = decDay2;
        obj['decDay3'] = decDay3;
        obj['decDay4'] = decDay4;
        obj['decDay5'] = decDay5;
        obj['decDay6'] = decDay6;
        obj['decDay7'] = decDay7;
        obj['decDay8'] = decDay8;
        obj['decDay9'] = decDay9;
        obj['decDay10'] = decDay10;
        obj['decDay11'] = decDay11;
        obj['decDay12'] = decDay12;
        obj['decDay13'] = decDay13;
        obj['decDay14'] = decDay14;
        obj['decDay15'] = decDay15;
        obj['decDay16'] = decDay16;
        obj['decDay17'] = decDay17;
        obj['decDay18'] = decDay18;
        obj['decDay19'] = decDay19;
        obj['decDay20'] = decDay20;
        obj['decDay21'] = decDay21;
        obj['employeeDec'] = employeeDec;
    }

    /**
     * Constructs a <code>December</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/December} obj Optional instance to populate.
     * @return {module:model/December} The populated <code>December</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new December();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('decDay1')) {
                obj['decDay1'] = ApiClient.convertToType(data['decDay1'], 'String');
            }
            if (data.hasOwnProperty('decDay2')) {
                obj['decDay2'] = ApiClient.convertToType(data['decDay2'], 'String');
            }
            if (data.hasOwnProperty('decDay3')) {
                obj['decDay3'] = ApiClient.convertToType(data['decDay3'], 'String');
            }
            if (data.hasOwnProperty('decDay4')) {
                obj['decDay4'] = ApiClient.convertToType(data['decDay4'], 'String');
            }
            if (data.hasOwnProperty('decDay5')) {
                obj['decDay5'] = ApiClient.convertToType(data['decDay5'], 'String');
            }
            if (data.hasOwnProperty('decDay6')) {
                obj['decDay6'] = ApiClient.convertToType(data['decDay6'], 'String');
            }
            if (data.hasOwnProperty('decDay7')) {
                obj['decDay7'] = ApiClient.convertToType(data['decDay7'], 'String');
            }
            if (data.hasOwnProperty('decDay8')) {
                obj['decDay8'] = ApiClient.convertToType(data['decDay8'], 'String');
            }
            if (data.hasOwnProperty('decDay9')) {
                obj['decDay9'] = ApiClient.convertToType(data['decDay9'], 'String');
            }
            if (data.hasOwnProperty('decDay10')) {
                obj['decDay10'] = ApiClient.convertToType(data['decDay10'], 'String');
            }
            if (data.hasOwnProperty('decDay11')) {
                obj['decDay11'] = ApiClient.convertToType(data['decDay11'], 'String');
            }
            if (data.hasOwnProperty('decDay12')) {
                obj['decDay12'] = ApiClient.convertToType(data['decDay12'], 'String');
            }
            if (data.hasOwnProperty('decDay13')) {
                obj['decDay13'] = ApiClient.convertToType(data['decDay13'], 'String');
            }
            if (data.hasOwnProperty('decDay14')) {
                obj['decDay14'] = ApiClient.convertToType(data['decDay14'], 'String');
            }
            if (data.hasOwnProperty('decDay15')) {
                obj['decDay15'] = ApiClient.convertToType(data['decDay15'], 'String');
            }
            if (data.hasOwnProperty('decDay16')) {
                obj['decDay16'] = ApiClient.convertToType(data['decDay16'], 'String');
            }
            if (data.hasOwnProperty('decDay17')) {
                obj['decDay17'] = ApiClient.convertToType(data['decDay17'], 'String');
            }
            if (data.hasOwnProperty('decDay18')) {
                obj['decDay18'] = ApiClient.convertToType(data['decDay18'], 'String');
            }
            if (data.hasOwnProperty('decDay19')) {
                obj['decDay19'] = ApiClient.convertToType(data['decDay19'], 'String');
            }
            if (data.hasOwnProperty('decDay20')) {
                obj['decDay20'] = ApiClient.convertToType(data['decDay20'], 'String');
            }
            if (data.hasOwnProperty('decDay21')) {
                obj['decDay21'] = ApiClient.convertToType(data['decDay21'], 'String');
            }
            if (data.hasOwnProperty('employeeDec')) {
                obj['employeeDec'] = ApiClient.convertToType(data['employeeDec'], User);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
December.prototype['_id'] = undefined;

/**
 * @member {String} decDay1
 */
December.prototype['decDay1'] = undefined;

/**
 * @member {String} decDay2
 */
December.prototype['decDay2'] = undefined;

/**
 * @member {String} decDay3
 */
December.prototype['decDay3'] = undefined;

/**
 * @member {String} decDay4
 */
December.prototype['decDay4'] = undefined;

/**
 * @member {String} decDay5
 */
December.prototype['decDay5'] = undefined;

/**
 * @member {String} decDay6
 */
December.prototype['decDay6'] = undefined;

/**
 * @member {String} decDay7
 */
December.prototype['decDay7'] = undefined;

/**
 * @member {String} decDay8
 */
December.prototype['decDay8'] = undefined;

/**
 * @member {String} decDay9
 */
December.prototype['decDay9'] = undefined;

/**
 * @member {String} decDay10
 */
December.prototype['decDay10'] = undefined;

/**
 * @member {String} decDay11
 */
December.prototype['decDay11'] = undefined;

/**
 * @member {String} decDay12
 */
December.prototype['decDay12'] = undefined;

/**
 * @member {String} decDay13
 */
December.prototype['decDay13'] = undefined;

/**
 * @member {String} decDay14
 */
December.prototype['decDay14'] = undefined;

/**
 * @member {String} decDay15
 */
December.prototype['decDay15'] = undefined;

/**
 * @member {String} decDay16
 */
December.prototype['decDay16'] = undefined;

/**
 * @member {String} decDay17
 */
December.prototype['decDay17'] = undefined;

/**
 * @member {String} decDay18
 */
December.prototype['decDay18'] = undefined;

/**
 * @member {String} decDay19
 */
December.prototype['decDay19'] = undefined;

/**
 * @member {String} decDay20
 */
December.prototype['decDay20'] = undefined;

/**
 * @member {String} decDay21
 */
December.prototype['decDay21'] = undefined;

/**
 * @member {module:model/User} employeeDec
 */
December.prototype['employeeDec'] = undefined;






export default December;

