/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Day from './Day';

/**
 * The Month model module.
 * @module model/Month
 * @version 1.0.0
 */
class Month {
    /**
     * Constructs a new <code>Month</code>.
     * @alias module:model/Month
     * @param monthName {String} 
     * @param monthId {String} 
     * @param monthDay {Array.<module:model/Day>} 
     */
    constructor(monthName, monthId, monthDay) { 
        
        Month.initialize(this, monthName, monthId, monthDay);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, monthName, monthId, monthDay) { 
        obj['monthName'] = monthName;
        obj['monthId'] = monthId;
        obj['monthDay'] = monthDay;
    }

    /**
     * Constructs a <code>Month</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Month} obj Optional instance to populate.
     * @return {module:model/Month} The populated <code>Month</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Month();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('monthName')) {
                obj['monthName'] = ApiClient.convertToType(data['monthName'], 'String');
            }
            if (data.hasOwnProperty('monthId')) {
                obj['monthId'] = ApiClient.convertToType(data['monthId'], 'String');
            }
            if (data.hasOwnProperty('monthDay')) {
                obj['monthDay'] = ApiClient.convertToType(data['monthDay'], [Day]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Month.prototype['_id'] = undefined;

/**
 * @member {String} monthName
 */
Month.prototype['monthName'] = undefined;

/**
 * @member {String} monthId
 */
Month.prototype['monthId'] = undefined;

/**
 * @member {Array.<module:model/Day>} monthDay
 */
Month.prototype['monthDay'] = undefined;






export default Month;

