/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The November model module.
 * @module model/November
 * @version 1.0.0
 */
class November {
    /**
     * Constructs a new <code>November</code>.
     * @alias module:model/November
     * @param novDay1 {String} 
     * @param novDay2 {String} 
     * @param novDay3 {String} 
     * @param novDay4 {String} 
     * @param novDay5 {String} 
     * @param novDay6 {String} 
     * @param novDay7 {String} 
     * @param novDay8 {String} 
     * @param novDay9 {String} 
     * @param novDay10 {String} 
     * @param novDay11 {String} 
     * @param novDay12 {String} 
     * @param novDay13 {String} 
     * @param novDay14 {String} 
     * @param novDay15 {String} 
     * @param novDay16 {String} 
     * @param novDay17 {String} 
     * @param novDay18 {String} 
     * @param novDay19 {String} 
     * @param novDay20 {String} 
     * @param novDay21 {String} 
     * @param novDay22 {String} 
     * @param employeeNov {module:model/User} 
     */
    constructor(novDay1, novDay2, novDay3, novDay4, novDay5, novDay6, novDay7, novDay8, novDay9, novDay10, novDay11, novDay12, novDay13, novDay14, novDay15, novDay16, novDay17, novDay18, novDay19, novDay20, novDay21, novDay22, employeeNov) { 
        
        November.initialize(this, novDay1, novDay2, novDay3, novDay4, novDay5, novDay6, novDay7, novDay8, novDay9, novDay10, novDay11, novDay12, novDay13, novDay14, novDay15, novDay16, novDay17, novDay18, novDay19, novDay20, novDay21, novDay22, employeeNov);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, novDay1, novDay2, novDay3, novDay4, novDay5, novDay6, novDay7, novDay8, novDay9, novDay10, novDay11, novDay12, novDay13, novDay14, novDay15, novDay16, novDay17, novDay18, novDay19, novDay20, novDay21, novDay22, employeeNov) { 
        obj['novDay1'] = novDay1;
        obj['novDay2'] = novDay2;
        obj['novDay3'] = novDay3;
        obj['novDay4'] = novDay4;
        obj['novDay5'] = novDay5;
        obj['novDay6'] = novDay6;
        obj['novDay7'] = novDay7;
        obj['novDay8'] = novDay8;
        obj['novDay9'] = novDay9;
        obj['novDay10'] = novDay10;
        obj['novDay11'] = novDay11;
        obj['novDay12'] = novDay12;
        obj['novDay13'] = novDay13;
        obj['novDay14'] = novDay14;
        obj['novDay15'] = novDay15;
        obj['novDay16'] = novDay16;
        obj['novDay17'] = novDay17;
        obj['novDay18'] = novDay18;
        obj['novDay19'] = novDay19;
        obj['novDay20'] = novDay20;
        obj['novDay21'] = novDay21;
        obj['novDay22'] = novDay22;
        obj['employeeNov'] = employeeNov;
    }

    /**
     * Constructs a <code>November</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/November} obj Optional instance to populate.
     * @return {module:model/November} The populated <code>November</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new November();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('novDay1')) {
                obj['novDay1'] = ApiClient.convertToType(data['novDay1'], 'String');
            }
            if (data.hasOwnProperty('novDay2')) {
                obj['novDay2'] = ApiClient.convertToType(data['novDay2'], 'String');
            }
            if (data.hasOwnProperty('novDay3')) {
                obj['novDay3'] = ApiClient.convertToType(data['novDay3'], 'String');
            }
            if (data.hasOwnProperty('novDay4')) {
                obj['novDay4'] = ApiClient.convertToType(data['novDay4'], 'String');
            }
            if (data.hasOwnProperty('novDay5')) {
                obj['novDay5'] = ApiClient.convertToType(data['novDay5'], 'String');
            }
            if (data.hasOwnProperty('novDay6')) {
                obj['novDay6'] = ApiClient.convertToType(data['novDay6'], 'String');
            }
            if (data.hasOwnProperty('novDay7')) {
                obj['novDay7'] = ApiClient.convertToType(data['novDay7'], 'String');
            }
            if (data.hasOwnProperty('novDay8')) {
                obj['novDay8'] = ApiClient.convertToType(data['novDay8'], 'String');
            }
            if (data.hasOwnProperty('novDay9')) {
                obj['novDay9'] = ApiClient.convertToType(data['novDay9'], 'String');
            }
            if (data.hasOwnProperty('novDay10')) {
                obj['novDay10'] = ApiClient.convertToType(data['novDay10'], 'String');
            }
            if (data.hasOwnProperty('novDay11')) {
                obj['novDay11'] = ApiClient.convertToType(data['novDay11'], 'String');
            }
            if (data.hasOwnProperty('novDay12')) {
                obj['novDay12'] = ApiClient.convertToType(data['novDay12'], 'String');
            }
            if (data.hasOwnProperty('novDay13')) {
                obj['novDay13'] = ApiClient.convertToType(data['novDay13'], 'String');
            }
            if (data.hasOwnProperty('novDay14')) {
                obj['novDay14'] = ApiClient.convertToType(data['novDay14'], 'String');
            }
            if (data.hasOwnProperty('novDay15')) {
                obj['novDay15'] = ApiClient.convertToType(data['novDay15'], 'String');
            }
            if (data.hasOwnProperty('novDay16')) {
                obj['novDay16'] = ApiClient.convertToType(data['novDay16'], 'String');
            }
            if (data.hasOwnProperty('novDay17')) {
                obj['novDay17'] = ApiClient.convertToType(data['novDay17'], 'String');
            }
            if (data.hasOwnProperty('novDay18')) {
                obj['novDay18'] = ApiClient.convertToType(data['novDay18'], 'String');
            }
            if (data.hasOwnProperty('novDay19')) {
                obj['novDay19'] = ApiClient.convertToType(data['novDay19'], 'String');
            }
            if (data.hasOwnProperty('novDay20')) {
                obj['novDay20'] = ApiClient.convertToType(data['novDay20'], 'String');
            }
            if (data.hasOwnProperty('novDay21')) {
                obj['novDay21'] = ApiClient.convertToType(data['novDay21'], 'String');
            }
            if (data.hasOwnProperty('novDay22')) {
                obj['novDay22'] = ApiClient.convertToType(data['novDay22'], 'String');
            }
            if (data.hasOwnProperty('employeeNov')) {
                obj['employeeNov'] = ApiClient.convertToType(data['employeeNov'], User);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
November.prototype['_id'] = undefined;

/**
 * @member {String} novDay1
 */
November.prototype['novDay1'] = undefined;

/**
 * @member {String} novDay2
 */
November.prototype['novDay2'] = undefined;

/**
 * @member {String} novDay3
 */
November.prototype['novDay3'] = undefined;

/**
 * @member {String} novDay4
 */
November.prototype['novDay4'] = undefined;

/**
 * @member {String} novDay5
 */
November.prototype['novDay5'] = undefined;

/**
 * @member {String} novDay6
 */
November.prototype['novDay6'] = undefined;

/**
 * @member {String} novDay7
 */
November.prototype['novDay7'] = undefined;

/**
 * @member {String} novDay8
 */
November.prototype['novDay8'] = undefined;

/**
 * @member {String} novDay9
 */
November.prototype['novDay9'] = undefined;

/**
 * @member {String} novDay10
 */
November.prototype['novDay10'] = undefined;

/**
 * @member {String} novDay11
 */
November.prototype['novDay11'] = undefined;

/**
 * @member {String} novDay12
 */
November.prototype['novDay12'] = undefined;

/**
 * @member {String} novDay13
 */
November.prototype['novDay13'] = undefined;

/**
 * @member {String} novDay14
 */
November.prototype['novDay14'] = undefined;

/**
 * @member {String} novDay15
 */
November.prototype['novDay15'] = undefined;

/**
 * @member {String} novDay16
 */
November.prototype['novDay16'] = undefined;

/**
 * @member {String} novDay17
 */
November.prototype['novDay17'] = undefined;

/**
 * @member {String} novDay18
 */
November.prototype['novDay18'] = undefined;

/**
 * @member {String} novDay19
 */
November.prototype['novDay19'] = undefined;

/**
 * @member {String} novDay20
 */
November.prototype['novDay20'] = undefined;

/**
 * @member {String} novDay21
 */
November.prototype['novDay21'] = undefined;

/**
 * @member {String} novDay22
 */
November.prototype['novDay22'] = undefined;

/**
 * @member {module:model/User} employeeNov
 */
November.prototype['employeeNov'] = undefined;






export default November;

