/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import User from './User';

/**
 * The September model module.
 * @module model/September
 * @version 1.0.0
 */
class September {
    /**
     * Constructs a new <code>September</code>.
     * @alias module:model/September
     * @param employeeSept {module:model/User} 
     * @param septDay1 {String} 
     * @param septDay2 {String} 
     * @param septDay3 {String} 
     * @param septDay4 {String} 
     * @param septDay5 {String} 
     * @param septDay6 {String} 
     * @param septDay7 {String} 
     * @param septDay8 {String} 
     * @param septDay9 {String} 
     * @param septDay10 {String} 
     * @param septDay11 {String} 
     * @param septDay12 {String} 
     * @param septDay13 {String} 
     * @param septDay14 {String} 
     * @param septDay15 {String} 
     * @param septDay16 {String} 
     * @param septDay17 {String} 
     * @param septDay18 {String} 
     * @param septDay19 {String} 
     * @param septDay20 {String} 
     * @param septDay21 {String} 
     */
    constructor(employeeSept, septDay1, septDay2, septDay3, septDay4, septDay5, septDay6, septDay7, septDay8, septDay9, septDay10, septDay11, septDay12, septDay13, septDay14, septDay15, septDay16, septDay17, septDay18, septDay19, septDay20, septDay21) { 
        
        September.initialize(this, employeeSept, septDay1, septDay2, septDay3, septDay4, septDay5, septDay6, septDay7, septDay8, septDay9, septDay10, septDay11, septDay12, septDay13, septDay14, septDay15, septDay16, septDay17, septDay18, septDay19, septDay20, septDay21);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, employeeSept, septDay1, septDay2, septDay3, septDay4, septDay5, septDay6, septDay7, septDay8, septDay9, septDay10, septDay11, septDay12, septDay13, septDay14, septDay15, septDay16, septDay17, septDay18, septDay19, septDay20, septDay21) { 
        obj['employeeSept'] = employeeSept;
        obj['septDay1'] = septDay1;
        obj['septDay2'] = septDay2;
        obj['septDay3'] = septDay3;
        obj['septDay4'] = septDay4;
        obj['septDay5'] = septDay5;
        obj['septDay6'] = septDay6;
        obj['septDay7'] = septDay7;
        obj['septDay8'] = septDay8;
        obj['septDay9'] = septDay9;
        obj['septDay10'] = septDay10;
        obj['septDay11'] = septDay11;
        obj['septDay12'] = septDay12;
        obj['septDay13'] = septDay13;
        obj['septDay14'] = septDay14;
        obj['septDay15'] = septDay15;
        obj['septDay16'] = septDay16;
        obj['septDay17'] = septDay17;
        obj['septDay18'] = septDay18;
        obj['septDay19'] = septDay19;
        obj['septDay20'] = septDay20;
        obj['septDay21'] = septDay21;
    }

    /**
     * Constructs a <code>September</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/September} obj Optional instance to populate.
     * @return {module:model/September} The populated <code>September</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new September();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('employeeSept')) {
                obj['employeeSept'] = ApiClient.convertToType(data['employeeSept'], User);
            }
            if (data.hasOwnProperty('septDay1')) {
                obj['septDay1'] = ApiClient.convertToType(data['septDay1'], 'String');
            }
            if (data.hasOwnProperty('septDay2')) {
                obj['septDay2'] = ApiClient.convertToType(data['septDay2'], 'String');
            }
            if (data.hasOwnProperty('septDay3')) {
                obj['septDay3'] = ApiClient.convertToType(data['septDay3'], 'String');
            }
            if (data.hasOwnProperty('septDay4')) {
                obj['septDay4'] = ApiClient.convertToType(data['septDay4'], 'String');
            }
            if (data.hasOwnProperty('septDay5')) {
                obj['septDay5'] = ApiClient.convertToType(data['septDay5'], 'String');
            }
            if (data.hasOwnProperty('septDay6')) {
                obj['septDay6'] = ApiClient.convertToType(data['septDay6'], 'String');
            }
            if (data.hasOwnProperty('septDay7')) {
                obj['septDay7'] = ApiClient.convertToType(data['septDay7'], 'String');
            }
            if (data.hasOwnProperty('septDay8')) {
                obj['septDay8'] = ApiClient.convertToType(data['septDay8'], 'String');
            }
            if (data.hasOwnProperty('septDay9')) {
                obj['septDay9'] = ApiClient.convertToType(data['septDay9'], 'String');
            }
            if (data.hasOwnProperty('septDay10')) {
                obj['septDay10'] = ApiClient.convertToType(data['septDay10'], 'String');
            }
            if (data.hasOwnProperty('septDay11')) {
                obj['septDay11'] = ApiClient.convertToType(data['septDay11'], 'String');
            }
            if (data.hasOwnProperty('septDay12')) {
                obj['septDay12'] = ApiClient.convertToType(data['septDay12'], 'String');
            }
            if (data.hasOwnProperty('septDay13')) {
                obj['septDay13'] = ApiClient.convertToType(data['septDay13'], 'String');
            }
            if (data.hasOwnProperty('septDay14')) {
                obj['septDay14'] = ApiClient.convertToType(data['septDay14'], 'String');
            }
            if (data.hasOwnProperty('septDay15')) {
                obj['septDay15'] = ApiClient.convertToType(data['septDay15'], 'String');
            }
            if (data.hasOwnProperty('septDay16')) {
                obj['septDay16'] = ApiClient.convertToType(data['septDay16'], 'String');
            }
            if (data.hasOwnProperty('septDay17')) {
                obj['septDay17'] = ApiClient.convertToType(data['septDay17'], 'String');
            }
            if (data.hasOwnProperty('septDay18')) {
                obj['septDay18'] = ApiClient.convertToType(data['septDay18'], 'String');
            }
            if (data.hasOwnProperty('septDay19')) {
                obj['septDay19'] = ApiClient.convertToType(data['septDay19'], 'String');
            }
            if (data.hasOwnProperty('septDay20')) {
                obj['septDay20'] = ApiClient.convertToType(data['septDay20'], 'String');
            }
            if (data.hasOwnProperty('septDay21')) {
                obj['septDay21'] = ApiClient.convertToType(data['septDay21'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
September.prototype['_id'] = undefined;

/**
 * @member {module:model/User} employeeSept
 */
September.prototype['employeeSept'] = undefined;

/**
 * @member {String} septDay1
 */
September.prototype['septDay1'] = undefined;

/**
 * @member {String} septDay2
 */
September.prototype['septDay2'] = undefined;

/**
 * @member {String} septDay3
 */
September.prototype['septDay3'] = undefined;

/**
 * @member {String} septDay4
 */
September.prototype['septDay4'] = undefined;

/**
 * @member {String} septDay5
 */
September.prototype['septDay5'] = undefined;

/**
 * @member {String} septDay6
 */
September.prototype['septDay6'] = undefined;

/**
 * @member {String} septDay7
 */
September.prototype['septDay7'] = undefined;

/**
 * @member {String} septDay8
 */
September.prototype['septDay8'] = undefined;

/**
 * @member {String} septDay9
 */
September.prototype['septDay9'] = undefined;

/**
 * @member {String} septDay10
 */
September.prototype['septDay10'] = undefined;

/**
 * @member {String} septDay11
 */
September.prototype['septDay11'] = undefined;

/**
 * @member {String} septDay12
 */
September.prototype['septDay12'] = undefined;

/**
 * @member {String} septDay13
 */
September.prototype['septDay13'] = undefined;

/**
 * @member {String} septDay14
 */
September.prototype['septDay14'] = undefined;

/**
 * @member {String} septDay15
 */
September.prototype['septDay15'] = undefined;

/**
 * @member {String} septDay16
 */
September.prototype['septDay16'] = undefined;

/**
 * @member {String} septDay17
 */
September.prototype['septDay17'] = undefined;

/**
 * @member {String} septDay18
 */
September.prototype['septDay18'] = undefined;

/**
 * @member {String} septDay19
 */
September.prototype['septDay19'] = undefined;

/**
 * @member {String} septDay20
 */
September.prototype['septDay20'] = undefined;

/**
 * @member {String} septDay21
 */
September.prototype['septDay21'] = undefined;






export default September;

