/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Project from './Project';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     * @param userName {String} 
     * @param userSurname {String} 
     * @param userProject {Array.<module:model/Project>} 
     */
    constructor(userName, userSurname, userProject) { 
        
        User.initialize(this, userName, userSurname, userProject);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, userName, userSurname, userProject) { 
        obj['userName'] = userName;
        obj['userSurname'] = userSurname;
        obj['userProject'] = userProject;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('userSurname')) {
                obj['userSurname'] = ApiClient.convertToType(data['userSurname'], 'String');
            }
            if (data.hasOwnProperty('userProject')) {
                obj['userProject'] = ApiClient.convertToType(data['userProject'], [Project]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
User.prototype['_id'] = undefined;

/**
 * @member {String} userName
 */
User.prototype['userName'] = undefined;

/**
 * @member {String} userSurname
 */
User.prototype['userSurname'] = undefined;

/**
 * @member {Array.<module:model/Project>} userProject
 */
User.prototype['userProject'] = undefined;






export default User;

