/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Month from './Month';

/**
 * The Workpackage model module.
 * @module model/Workpackage
 * @version 1.0.0
 */
class Workpackage {
    /**
     * Constructs a new <code>Workpackage</code>.
     * @alias module:model/Workpackage
     * @param workpackageId {String} 
     * @param workpackageName {String} 
     * @param workpackageMonth {Array.<module:model/Month>} 
     */
    constructor(workpackageId, workpackageName, workpackageMonth) { 
        
        Workpackage.initialize(this, workpackageId, workpackageName, workpackageMonth);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, workpackageId, workpackageName, workpackageMonth) { 
        obj['workpackageId'] = workpackageId;
        obj['workpackageName'] = workpackageName;
        obj['workpackageMonth'] = workpackageMonth;
    }

    /**
     * Constructs a <code>Workpackage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Workpackage} obj Optional instance to populate.
     * @return {module:model/Workpackage} The populated <code>Workpackage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Workpackage();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('workpackageId')) {
                obj['workpackageId'] = ApiClient.convertToType(data['workpackageId'], 'String');
            }
            if (data.hasOwnProperty('workpackageName')) {
                obj['workpackageName'] = ApiClient.convertToType(data['workpackageName'], 'String');
            }
            if (data.hasOwnProperty('workpackageMonth')) {
                obj['workpackageMonth'] = ApiClient.convertToType(data['workpackageMonth'], [Month]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Workpackage.prototype['_id'] = undefined;

/**
 * @member {String} workpackageId
 */
Workpackage.prototype['workpackageId'] = undefined;

/**
 * @member {String} workpackageName
 */
Workpackage.prototype['workpackageName'] = undefined;

/**
 * @member {Array.<module:model/Month>} workpackageMonth
 */
Workpackage.prototype['workpackageMonth'] = undefined;






export default Workpackage;

