/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.August();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('August', function() {
    it('should create an instance of August', function() {
      // uncomment below and update the code to test August
      //var instane = new TempApi.August();
      //expect(instance).to.be.a(TempApi.August);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property employee (base name: "employee")', function() {
      // uncomment below and update the code to test the property employee
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day1 (base name: "day1")', function() {
      // uncomment below and update the code to test the property day1
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day2 (base name: "day2")', function() {
      // uncomment below and update the code to test the property day2
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day3 (base name: "day3")', function() {
      // uncomment below and update the code to test the property day3
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day4 (base name: "day4")', function() {
      // uncomment below and update the code to test the property day4
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day5 (base name: "day5")', function() {
      // uncomment below and update the code to test the property day5
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day6 (base name: "day6")', function() {
      // uncomment below and update the code to test the property day6
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day7 (base name: "day7")', function() {
      // uncomment below and update the code to test the property day7
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day8 (base name: "day8")', function() {
      // uncomment below and update the code to test the property day8
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day9 (base name: "day9")', function() {
      // uncomment below and update the code to test the property day9
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day10 (base name: "day10")', function() {
      // uncomment below and update the code to test the property day10
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day11 (base name: "day11")', function() {
      // uncomment below and update the code to test the property day11
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day12 (base name: "day12")', function() {
      // uncomment below and update the code to test the property day12
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day13 (base name: "day13")', function() {
      // uncomment below and update the code to test the property day13
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day14 (base name: "day14")', function() {
      // uncomment below and update the code to test the property day14
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day15 (base name: "day15")', function() {
      // uncomment below and update the code to test the property day15
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day16 (base name: "day16")', function() {
      // uncomment below and update the code to test the property day16
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day17 (base name: "day17")', function() {
      // uncomment below and update the code to test the property day17
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day18 (base name: "day18")', function() {
      // uncomment below and update the code to test the property day18
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day19 (base name: "day19")', function() {
      // uncomment below and update the code to test the property day19
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day20 (base name: "day20")', function() {
      // uncomment below and update the code to test the property day20
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day21 (base name: "day21")', function() {
      // uncomment below and update the code to test the property day21
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

    it('should have the property day22 (base name: "day22")', function() {
      // uncomment below and update the code to test the property day22
      //var instance = new TempApi.August();
      //expect(instance).to.be();
    });

  });

}));
