/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.December();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('December', function() {
    it('should create an instance of December', function() {
      // uncomment below and update the code to test December
      //var instane = new TempApi.December();
      //expect(instance).to.be.a(TempApi.December);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay1 (base name: "decDay1")', function() {
      // uncomment below and update the code to test the property decDay1
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay2 (base name: "decDay2")', function() {
      // uncomment below and update the code to test the property decDay2
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay3 (base name: "decDay3")', function() {
      // uncomment below and update the code to test the property decDay3
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay4 (base name: "decDay4")', function() {
      // uncomment below and update the code to test the property decDay4
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay5 (base name: "decDay5")', function() {
      // uncomment below and update the code to test the property decDay5
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay6 (base name: "decDay6")', function() {
      // uncomment below and update the code to test the property decDay6
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay7 (base name: "decDay7")', function() {
      // uncomment below and update the code to test the property decDay7
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay8 (base name: "decDay8")', function() {
      // uncomment below and update the code to test the property decDay8
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay9 (base name: "decDay9")', function() {
      // uncomment below and update the code to test the property decDay9
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay10 (base name: "decDay10")', function() {
      // uncomment below and update the code to test the property decDay10
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay11 (base name: "decDay11")', function() {
      // uncomment below and update the code to test the property decDay11
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay12 (base name: "decDay12")', function() {
      // uncomment below and update the code to test the property decDay12
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay13 (base name: "decDay13")', function() {
      // uncomment below and update the code to test the property decDay13
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay14 (base name: "decDay14")', function() {
      // uncomment below and update the code to test the property decDay14
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay15 (base name: "decDay15")', function() {
      // uncomment below and update the code to test the property decDay15
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay16 (base name: "decDay16")', function() {
      // uncomment below and update the code to test the property decDay16
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay17 (base name: "decDay17")', function() {
      // uncomment below and update the code to test the property decDay17
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay18 (base name: "decDay18")', function() {
      // uncomment below and update the code to test the property decDay18
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay19 (base name: "decDay19")', function() {
      // uncomment below and update the code to test the property decDay19
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay20 (base name: "decDay20")', function() {
      // uncomment below and update the code to test the property decDay20
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property decDay21 (base name: "decDay21")', function() {
      // uncomment below and update the code to test the property decDay21
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

    it('should have the property employeeDec (base name: "employeeDec")', function() {
      // uncomment below and update the code to test the property employeeDec
      //var instance = new TempApi.December();
      //expect(instance).to.be();
    });

  });

}));
