/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.November();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('November', function() {
    it('should create an instance of November', function() {
      // uncomment below and update the code to test November
      //var instane = new TempApi.November();
      //expect(instance).to.be.a(TempApi.November);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay1 (base name: "novDay1")', function() {
      // uncomment below and update the code to test the property novDay1
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay2 (base name: "novDay2")', function() {
      // uncomment below and update the code to test the property novDay2
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay3 (base name: "novDay3")', function() {
      // uncomment below and update the code to test the property novDay3
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay4 (base name: "novDay4")', function() {
      // uncomment below and update the code to test the property novDay4
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay5 (base name: "novDay5")', function() {
      // uncomment below and update the code to test the property novDay5
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay6 (base name: "novDay6")', function() {
      // uncomment below and update the code to test the property novDay6
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay7 (base name: "novDay7")', function() {
      // uncomment below and update the code to test the property novDay7
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay8 (base name: "novDay8")', function() {
      // uncomment below and update the code to test the property novDay8
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay9 (base name: "novDay9")', function() {
      // uncomment below and update the code to test the property novDay9
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay10 (base name: "novDay10")', function() {
      // uncomment below and update the code to test the property novDay10
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay11 (base name: "novDay11")', function() {
      // uncomment below and update the code to test the property novDay11
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay12 (base name: "novDay12")', function() {
      // uncomment below and update the code to test the property novDay12
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay13 (base name: "novDay13")', function() {
      // uncomment below and update the code to test the property novDay13
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay14 (base name: "novDay14")', function() {
      // uncomment below and update the code to test the property novDay14
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay15 (base name: "novDay15")', function() {
      // uncomment below and update the code to test the property novDay15
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay16 (base name: "novDay16")', function() {
      // uncomment below and update the code to test the property novDay16
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay17 (base name: "novDay17")', function() {
      // uncomment below and update the code to test the property novDay17
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay18 (base name: "novDay18")', function() {
      // uncomment below and update the code to test the property novDay18
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay19 (base name: "novDay19")', function() {
      // uncomment below and update the code to test the property novDay19
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay20 (base name: "novDay20")', function() {
      // uncomment below and update the code to test the property novDay20
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay21 (base name: "novDay21")', function() {
      // uncomment below and update the code to test the property novDay21
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property novDay22 (base name: "novDay22")', function() {
      // uncomment below and update the code to test the property novDay22
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

    it('should have the property employeeNov (base name: "employeeNov")', function() {
      // uncomment below and update the code to test the property employeeNov
      //var instance = new TempApi.November();
      //expect(instance).to.be();
    });

  });

}));
