/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.October();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('October', function() {
    it('should create an instance of October', function() {
      // uncomment below and update the code to test October
      //var instane = new TempApi.October();
      //expect(instance).to.be.a(TempApi.October);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property employeeOct (base name: "employeeOct")', function() {
      // uncomment below and update the code to test the property employeeOct
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay1 (base name: "octDay1")', function() {
      // uncomment below and update the code to test the property octDay1
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay2 (base name: "octDay2")', function() {
      // uncomment below and update the code to test the property octDay2
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay3 (base name: "octDay3")', function() {
      // uncomment below and update the code to test the property octDay3
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay4 (base name: "octDay4")', function() {
      // uncomment below and update the code to test the property octDay4
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay5 (base name: "octDay5")', function() {
      // uncomment below and update the code to test the property octDay5
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay6 (base name: "octDay6")', function() {
      // uncomment below and update the code to test the property octDay6
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay7 (base name: "octDay7")', function() {
      // uncomment below and update the code to test the property octDay7
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay8 (base name: "octDay8")', function() {
      // uncomment below and update the code to test the property octDay8
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay9 (base name: "octDay9")', function() {
      // uncomment below and update the code to test the property octDay9
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay10 (base name: "octDay10")', function() {
      // uncomment below and update the code to test the property octDay10
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay11 (base name: "octDay11")', function() {
      // uncomment below and update the code to test the property octDay11
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay12 (base name: "octDay12")', function() {
      // uncomment below and update the code to test the property octDay12
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay13 (base name: "octDay13")', function() {
      // uncomment below and update the code to test the property octDay13
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay14 (base name: "octDay14")', function() {
      // uncomment below and update the code to test the property octDay14
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay15 (base name: "octDay15")', function() {
      // uncomment below and update the code to test the property octDay15
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay16 (base name: "octDay16")', function() {
      // uncomment below and update the code to test the property octDay16
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay17 (base name: "octDay17")', function() {
      // uncomment below and update the code to test the property octDay17
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay18 (base name: "octDay18")', function() {
      // uncomment below and update the code to test the property octDay18
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay20 (base name: "octDay20")', function() {
      // uncomment below and update the code to test the property octDay20
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay21 (base name: "octDay21")', function() {
      // uncomment below and update the code to test the property octDay21
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

    it('should have the property octDay22 (base name: "octDay22")', function() {
      // uncomment below and update the code to test the property octDay22
      //var instance = new TempApi.October();
      //expect(instance).to.be();
    });

  });

}));
