/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.September();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('September', function() {
    it('should create an instance of September', function() {
      // uncomment below and update the code to test September
      //var instane = new TempApi.September();
      //expect(instance).to.be.a(TempApi.September);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property employeeSept (base name: "employeeSept")', function() {
      // uncomment below and update the code to test the property employeeSept
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay1 (base name: "septDay1")', function() {
      // uncomment below and update the code to test the property septDay1
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay2 (base name: "septDay2")', function() {
      // uncomment below and update the code to test the property septDay2
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay3 (base name: "septDay3")', function() {
      // uncomment below and update the code to test the property septDay3
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay4 (base name: "septDay4")', function() {
      // uncomment below and update the code to test the property septDay4
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay5 (base name: "septDay5")', function() {
      // uncomment below and update the code to test the property septDay5
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay6 (base name: "septDay6")', function() {
      // uncomment below and update the code to test the property septDay6
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay7 (base name: "septDay7")', function() {
      // uncomment below and update the code to test the property septDay7
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay8 (base name: "septDay8")', function() {
      // uncomment below and update the code to test the property septDay8
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay9 (base name: "septDay9")', function() {
      // uncomment below and update the code to test the property septDay9
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay10 (base name: "septDay10")', function() {
      // uncomment below and update the code to test the property septDay10
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay11 (base name: "septDay11")', function() {
      // uncomment below and update the code to test the property septDay11
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay12 (base name: "septDay12")', function() {
      // uncomment below and update the code to test the property septDay12
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay13 (base name: "septDay13")', function() {
      // uncomment below and update the code to test the property septDay13
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay14 (base name: "septDay14")', function() {
      // uncomment below and update the code to test the property septDay14
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay15 (base name: "septDay15")', function() {
      // uncomment below and update the code to test the property septDay15
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay16 (base name: "septDay16")', function() {
      // uncomment below and update the code to test the property septDay16
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay17 (base name: "septDay17")', function() {
      // uncomment below and update the code to test the property septDay17
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay18 (base name: "septDay18")', function() {
      // uncomment below and update the code to test the property septDay18
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay19 (base name: "septDay19")', function() {
      // uncomment below and update the code to test the property septDay19
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay20 (base name: "septDay20")', function() {
      // uncomment below and update the code to test the property septDay20
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

    it('should have the property septDay21 (base name: "septDay21")', function() {
      // uncomment below and update the code to test the property septDay21
      //var instance = new TempApi.September();
      //expect(instance).to.be();
    });

  });

}));
