/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import August from './model/August';
import Day from './model/Day';
import December from './model/December';
import Month from './model/Month';
import November from './model/November';
import October from './model/October';
import Project from './model/Project';
import September from './model/September';
import User from './model/User';
import Workpackage from './model/Workpackage';
import AugustApi from './api/AugustApi';
import DayApi from './api/DayApi';
import DecemberApi from './api/DecemberApi';
import MonthApi from './api/MonthApi';
import NovemberApi from './api/NovemberApi';
import OctoberApi from './api/OctoberApi';
import ProjectApi from './api/ProjectApi';
import SeptemberApi from './api/SeptemberApi';
import UserApi from './api/UserApi';
import WorkpackageApi from './api/WorkpackageApi';


/**
* This_is_a_sample_openApi_document.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var TempApi = require('index'); // See note below*.
* var xxxSvc = new TempApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new TempApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new TempApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new TempApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The August model constructor.
     * @property {module:model/August}
     */
    August,

    /**
     * The Day model constructor.
     * @property {module:model/Day}
     */
    Day,

    /**
     * The December model constructor.
     * @property {module:model/December}
     */
    December,

    /**
     * The Month model constructor.
     * @property {module:model/Month}
     */
    Month,

    /**
     * The November model constructor.
     * @property {module:model/November}
     */
    November,

    /**
     * The October model constructor.
     * @property {module:model/October}
     */
    October,

    /**
     * The Project model constructor.
     * @property {module:model/Project}
     */
    Project,

    /**
     * The September model constructor.
     * @property {module:model/September}
     */
    September,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The Workpackage model constructor.
     * @property {module:model/Workpackage}
     */
    Workpackage,

    /**
    * The AugustApi service constructor.
    * @property {module:api/AugustApi}
    */
    AugustApi,

    /**
    * The DayApi service constructor.
    * @property {module:api/DayApi}
    */
    DayApi,

    /**
    * The DecemberApi service constructor.
    * @property {module:api/DecemberApi}
    */
    DecemberApi,

    /**
    * The MonthApi service constructor.
    * @property {module:api/MonthApi}
    */
    MonthApi,

    /**
    * The NovemberApi service constructor.
    * @property {module:api/NovemberApi}
    */
    NovemberApi,

    /**
    * The OctoberApi service constructor.
    * @property {module:api/OctoberApi}
    */
    OctoberApi,

    /**
    * The ProjectApi service constructor.
    * @property {module:api/ProjectApi}
    */
    ProjectApi,

    /**
    * The SeptemberApi service constructor.
    * @property {module:api/SeptemberApi}
    */
    SeptemberApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi,

    /**
    * The WorkpackageApi service constructor.
    * @property {module:api/WorkpackageApi}
    */
    WorkpackageApi
};

export default {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The August model constructor.
     * @property {module:model/August}
     */
    August,

    /**
     * The Day model constructor.
     * @property {module:model/Day}
     */
    Day,

    /**
     * The December model constructor.
     * @property {module:model/December}
     */
    December,

    /**
     * The Month model constructor.
     * @property {module:model/Month}
     */
    Month,

    /**
     * The November model constructor.
     * @property {module:model/November}
     */
    November,

    /**
     * The October model constructor.
     * @property {module:model/October}
     */
    October,

    /**
     * The Project model constructor.
     * @property {module:model/Project}
     */
    Project,

    /**
     * The September model constructor.
     * @property {module:model/September}
     */
    September,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The Workpackage model constructor.
     * @property {module:model/Workpackage}
     */
    Workpackage,

    /**
    * The AugustApi service constructor.
    * @property {module:api/AugustApi}
    */
    AugustApi,

    /**
    * The DayApi service constructor.
    * @property {module:api/DayApi}
    */
    DayApi,

    /**
    * The DecemberApi service constructor.
    * @property {module:api/DecemberApi}
    */
    DecemberApi,

    /**
    * The MonthApi service constructor.
    * @property {module:api/MonthApi}
    */
    MonthApi,

    /**
    * The NovemberApi service constructor.
    * @property {module:api/NovemberApi}
    */
    NovemberApi,

    /**
    * The OctoberApi service constructor.
    * @property {module:api/OctoberApi}
    */
    OctoberApi,

    /**
    * The ProjectApi service constructor.
    * @property {module:api/ProjectApi}
    */
    ProjectApi,

    /**
    * The SeptemberApi service constructor.
    * @property {module:api/SeptemberApi}
    */
    SeptemberApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi,

    /**
    * The WorkpackageApi service constructor.
    * @property {module:api/WorkpackageApi}
    */
    WorkpackageApi
};
