/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.AugustApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AugustApi', function() {
    describe('createaugust', function() {
      it('should call createaugust successfully', function(done) {
        //uncomment below and update the code to test createaugust
        //instance.createaugust(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteaugust', function() {
      it('should call deleteaugust successfully', function(done) {
        //uncomment below and update the code to test deleteaugust
        //instance.deleteaugust(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllaugust', function() {
      it('should call getAllaugust successfully', function(done) {
        //uncomment below and update the code to test getAllaugust
        //instance.getAllaugust(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getByParamsaugust', function() {
      it('should call getByParamsaugust successfully', function(done) {
        //uncomment below and update the code to test getByParamsaugust
        //instance.getByParamsaugust(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getaugust', function() {
      it('should call getaugust successfully', function(done) {
        //uncomment below and update the code to test getaugust
        //instance.getaugust(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateaugust', function() {
      it('should call updateaugust successfully', function(done) {
        //uncomment below and update the code to test updateaugust
        //instance.updateaugust(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
