/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.OctoberApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OctoberApi', function() {
    describe('createoctober', function() {
      it('should call createoctober successfully', function(done) {
        //uncomment below and update the code to test createoctober
        //instance.createoctober(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteoctober', function() {
      it('should call deleteoctober successfully', function(done) {
        //uncomment below and update the code to test deleteoctober
        //instance.deleteoctober(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAlloctober', function() {
      it('should call getAlloctober successfully', function(done) {
        //uncomment below and update the code to test getAlloctober
        //instance.getAlloctober(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getByParamsoctober', function() {
      it('should call getByParamsoctober successfully', function(done) {
        //uncomment below and update the code to test getByParamsoctober
        //instance.getByParamsoctober(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getoctober', function() {
      it('should call getoctober successfully', function(done) {
        //uncomment below and update the code to test getoctober
        //instance.getoctober(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateoctober', function() {
      it('should call updateoctober successfully', function(done) {
        //uncomment below and update the code to test updateoctober
        //instance.updateoctober(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
