/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.SeptemberApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SeptemberApi', function() {
    describe('createseptember', function() {
      it('should call createseptember successfully', function(done) {
        //uncomment below and update the code to test createseptember
        //instance.createseptember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteseptember', function() {
      it('should call deleteseptember successfully', function(done) {
        //uncomment below and update the code to test deleteseptember
        //instance.deleteseptember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllseptember', function() {
      it('should call getAllseptember successfully', function(done) {
        //uncomment below and update the code to test getAllseptember
        //instance.getAllseptember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getByParamsseptember', function() {
      it('should call getByParamsseptember successfully', function(done) {
        //uncomment below and update the code to test getByParamsseptember
        //instance.getByParamsseptember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getseptember', function() {
      it('should call getseptember successfully', function(done) {
        //uncomment below and update the code to test getseptember
        //instance.getseptember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateseptember', function() {
      it('should call updateseptember successfully', function(done) {
        //uncomment below and update the code to test updateseptember
        //instance.updateseptember(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
